package(default_visibility = ["//visibility:public"])

cc_library(
  name = "vector_ops",
  srcs = ["vector_ops.cc"],
  hdrs = ["vector_ops.h"],
)

cc_test(
  name = "vector_ops_test",
  srcs = ["vector_ops_test.cc"],
  deps = [
    ":vector_ops",
  ]
)