package(default_visibility = ["//visibility:public"])


cc_library(
  name="ray_tracing_processor",
  hdrs=["ray_tracing_processor.h"],
  deps = [
    "//core/models:camera",
    "//core/models:world",
    "//core/visual:canvas",
  ]
)