package(default_visibility=["//visibility:public"])

cc_binary(
  name = "chapter5_task",
  srcs = ["chapter5_task.cc"],
  deps = [
    "//core/ops:color_ops",
    "//core/visual:canvas",
    "//core/models:vector",
    "//core/ops:vector_ops",
    "//core/models:ray",
    "//core/models:world",
  ]
)